/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.heig.bdr.project;

import gg.jte.ContentType;
import gg.jte.TemplateEngine;
import gg.jte.resolve.DirectoryCodeResolver;
import io.javalin.Javalin;
import io.javalin.http.staticfiles.Location;
import io.javalin.rendering.template.JavalinJte;
import java.nio.file.Path;

/**
 * Main app for the project
 *
 * @author Rachel Tranchida
 * @author Rafael Dousse
 * @author Quentin Surdez
 */
public class App {
    static final int PORT = 7272;
    static Javalin app;


    public static void main(String[] args) {
        System.out.println("Basic server has started...");

        JavalinJte.init();
        app = setupApp().start(PORT);

    }

    public static Javalin setupApp() {
        JavalinJte.init(createTemplateEngine());

        Javalin app = Javalin.create(config -> {
            config.staticFiles.add("/static", Location.CLASSPATH);
        });

        //Routes
        var appControler = new AppControler();
        app.get("/", appControler::getInit);
        app.get("/character", appControler::getCharacter);
        app.get("/inventaire-character", appControler::getInventaireCharacter);
        app.get("/object/", appControler::getObject);
        app.get("/objectMarche/", appControler::getObjectMarche);
        app.get("/market", appControler::getMarket);
        return app;
    }

    // Configuration of JTE templates
    // Taken from the Javalin tutorials:
    // https://javalin.io/tutorials/jte#precompiling-templates
    private static TemplateEngine createTemplateEngine() {
        DirectoryCodeResolver codeResolver = new DirectoryCodeResolver(Path.of("src", "main", "jte"));
        return TemplateEngine.create(codeResolver, ContentType.Html);
    }
}
